SterlingMcKinley/FINAL_PROJECT

.github/workflows/Init-Remote-Statefile.yml
=> Use Region from config file

Terraform/Cluster_Production/alb.tf, Terraform/Cluster_Staging/alb.tf
Increase Intervals. 
Decrease Timeout.
=> Fix Terraform Files

.github/workflows/Build-and-Test.yml, .github/workflows/Deploy-Cluster.yml, .github/workflows/Init-Remote-Statefile.yml, .github/workflows/Redeploy-Cluster.yml, .github/workflows/Release-Cluster.yml
=> Fix Workflow Name

Docker/backend/assignmentapp/app/app.py, Docker/backend/userapp/app/app.py, Docker/frontend/app/www/index.html, Docker/frontend/app/www/js/script.js, Docker/frontend/app/www/registration.html, Docker/frontend/app/www/ss/home.html, Docker/frontend/app/www/ss/overview.html, Docker/frontend/app/www/ss/submissions.html
Grab instead of get. 
Fixed logout button. 
Made enter or submit for some pages the same as clicking in login or register.
=> Grab don't get

.github/workflows/Deploy-Cluster.yml, .github/workflows/Deploy-Cluster_Production.yml, .github/workflows/Redeploy-Cluster.yml, .github/workflows/Redeploy-Cluster_Production.yml, Docker/backend/assignmentapp/app/app.py, Docker/frontend/app/www/js/script.js
App Link in workflow. 
Fix Routes for backend. 
Loading Grades Part 1 Linking
=> App Link, Route fixes and Loading Grades Part 1

.github/workflows/Deploy-Cluster.yml, .github/workflows/Deploy-Cluster_Production.yml, .github/workflows/Redeploy-Cluster.yml, .github/workflows/Redeploy-Cluster_Production.yml, Docker/frontend/app/www/index.html, Docker/frontend/app/www/js/script.js, Docker/frontend/app/www/registration.html, Docker/frontend/app/www/ss/home.html, Docker/frontend/app/www/ss/overview.html
Remove extra http on App Link. 
On keypress checking for enter to submit when logging in and registering. 
Dynamically loading User data and Assignments.
=> Dynamic Loading User data and Assignments. 

Docker/frontend/app/www/index.html, Docker/frontend/app/www/registration.html
Stops triggering on any key press.
=> Fix pushing enter

Docker/frontend/app/www/js/script.js
Load key once to stop multiple reads, that may be causing read fails.
=> Load key once

Docker/frontend/app/www/ss/overview.html
=> LoadTable on clicking Submit

Docker/frontend/app/www/index.html, Docker/frontend/app/www/js/script.js, Docker/frontend/app/www/registration.html, Docker/frontend/app/www/ss/home.html, Docker/frontend/app/www/ss/overview.html, Docker/frontend/app/www/ss/submissions.html
Wait until page loads before running JavaScript. 
Fix being unable to type when entering password. 
Revert reading from session.
=> Fix entering password

Docker/frontend/app/www/registration.html
Click register instead of login
=> Click register instead of login

Docker/frontend/app/www/js/script.js
Pass Session API key instead of reading again.
=> Pass API key

Docker/frontend/app/www/js/script.js
Fixes the logic with loading page data.
=> Fix loading the page data

.github/workflows/Build-and-Test_Production.yml, .github/workflows/Deploy-Cluster_Production.yml, .github/workflows/Init-Remote-Statefile_Production.yml, .github/workflows/Redeploy-Cluster_Production.yml, .github/workflows/Release-Cluster_Production.yml
Production workflows will have environment: Production
=> Production workflows will have environment: Production

Docker/frontend/app/www/js/script.js
Loop to make sure data is loaded.
=> Loop to make sure data is loaded

Docker/frontend/app/www/js/script.js
=> Speed up loop

Docker/frontend/app/www/js/script.js
=> Fix routes

Docker/frontend/app/www/js/script.js
=> Fix routing of pages

Terraform/Cluster_Production/route53.tf, Terraform/Cluster_Staging/route53.tf
=> Route 53 to load balancers

Terraform/Cluster_Production/route53.tf, Terraform/Cluster_Staging/route53.tf
=> Remove http

Terraform/Cluster_Staging/ecs.tf
=> Metric alarms fixes. 

Terraform/Cluster_Production/route53.tf, Terraform/Cluster_Staging/route53.tf
=> Remove www

.github/workflows/Build-and-Test.yml, .github/workflows/Build-and-Test_Production.yml
Speed up unit tests using jobs
=> Speed up unit tests using jobs

.github/workflows/Build-and-Test_Production.yml, Terraform/Cluster_Production/route53.tf, Terraform/Cluster_Staging/route53.tf
Slight name change to work flows
=> Slight name change

Docker/frontend/app/www/js/script.js
=> fix who am i

Docker/frontend/app/www/js/script.js
=> Fix login to use navigate

Docker/frontend/app/www/admin/dashboard.html
Added script and fixed logout button
=> Added script and fixed logout button

Terraform/Database_Production/main.tf, Terraform/Database_Production/route53.tf, Terraform/Database_Production/terraform.tfvars, Terraform/Database_Production/variables.tf, Terraform/Database_Staging/main.tf, Terraform/Database_Staging/route53.tf, Terraform/Database_Staging/terraform.tfvars, Terraform/Database_Staging/variables.tf
=> RDS incomplete

.github/workflows/Deploy-Cluster.yml, .github/workflows/Deploy-Cluster_Production.yml, .github/workflows/Init-RDS Database.yml, .github/workflows/Init-RDS-Database_Production.yml, Terraform/Database_Production/main.tf, Terraform/Database_Production/route53.tf, Terraform/Database_Production/terraform.tfvars, Terraform/Database_Production/variables.tf, Terraform/Database_Staging/main.tf, Terraform/Database_Staging/route53.tf, Terraform/Database_Staging/terraform.tfvars, Terraform/Database_Staging/variables.tf
Complete terraform RDS files. 
Add RDS workflows.
=> RDS test 1

Terraform/Cluster_Staging/route53.tf, Terraform/Database_Production/route53.tf
=> dev -> test

.github/workflows/Deploy-Cluster.yml, .github/workflows/Deploy-Cluster_Production.yml, Docker/frontend/app/www/css/main.css
=> temp remove untested code

Docker/frontend/app/www/css/main.css
=> Test changing color

Docker/frontend/app/www/css/main.css, Docker/frontend/app/www/js/script.js, Docker/frontend/app/www/student/home.html
=> revert Test changing color

Docker/backend/userapp/app/app.py, Docker/frontend/app/www/admin/dashboard.html, Docker/frontend/app/www/js/script.js
Don't send passwords from backend. 
Admin dashboard page title: Document -> Admin Dashboard
Part 1 on loading students dynamically from the backend.
=> Backend Tweaks and Page title change

.github/workflows/Deploy-Cluster.yml, .github/workflows/Deploy-Cluster_Production.yml
Try to force redeploy of cluster
=> Try to force redeploy of cluster

.github/workflows/Deploy-Cluster.yml, .github/workflows/Deploy-Cluster_Production.yml, .github/workflows/Redeploy-Cluster.yml, .github/workflows/Redeploy-Cluster_Production.yml, .github/workflows/Release-Cluster.yml, .github/workflows/Release-Cluster_Production.yml, Terraform/Cluster_Production/route53.tf, Terraform/Cluster_Staging/route53.tf
Fix Force update cluster and comment out jq
Change url from load balancer to app
=> Fix Force update cluster and comment out jq

Terraform/Cluster_Staging/main.tf
Added force redeploy to staging
=> Added force redeploy to staging

Docker/frontend/app/www/index.html, Terraform/Cluster_Production/route53.tf, Terraform/Cluster_Staging/route53.tf, Terraform/Database_Production/route53.tf, Terraform/Database_Staging/route53.tf
Fix app link and test color change
=> Fix app link and test color change

.github/workflows/Deploy-Cluster.yml, .github/workflows/Deploy-Cluster_Production.yml
=> Force redeploy

Docker/frontend/app/www/js/script.js
=> Revert untested functions

Docker/frontend/app/www/index.html
=> Color change

Docker/frontend/app/www/index.html
=> revert Color change

Terraform/Cluster_Production/route53.tf, Terraform/Cluster_Staging/route53.tf, Terraform/Database_Production/route53.tf, Terraform/Database_Staging/route53.tf
=> Change sub domain www -> team

.github/workflows/Init-RDS Database.yml, .github/workflows/Init-RDS-Database_Production.yml
=> Fix RDS init

.github/workflows/Init-RDS Database.yml, .github/workflows/Init-RDS-Database_Production.yml
=> Fix RDS init secrets

.github/workflows/Deploy-Cluster.yml, .github/workflows/Deploy-Cluster_Production.yml, .github/workflows/Init-RDS Database.yml, .github/workflows/Init-RDS-Database_Production.yml, .github/workflows/Init-Remote-Statefile.yml, .github/workflows/Init-Remote-Statefile_Production.yml, .github/workflows/Redeploy-Cluster.yml, .github/workflows/Redeploy-Cluster_Production.yml, .github/workflows/Release-Cluster.yml, .github/workflows/Release-Cluster_Production.yml
Removed installing terraform and docker because runners come with it preinstalled
=> Removed installing terraform and docker because runners come with it preinstalled

.github/workflows/Deploy-Cluster.yml, .github/workflows/Deploy-Cluster_Production.yml, .github/workflows/Redeploy-Cluster.yml, .github/workflows/Redeploy-Cluster_Production.yml, Docker/backend/assignmentapp/app/app.py, Docker/backend/userapp/app/app.py, Terraform/Database_Production/route53.tf, Terraform/Database_Staging/route53.tf
Use RDS instead of container db
=> Use RDS instead of container db

.github/workflows/Deploy-Cluster.yml, .github/workflows/Deploy-Cluster_Production.yml, .github/workflows/Redeploy-Cluster.yml, .github/workflows/Redeploy-Cluster_Production.yml
=> Added Missing Secret

Terraform/Cluster_Production/main.tf, Terraform/Cluster_Staging/main.tf
Remove Terraform ECS Update in place causing bugs
=> Remove Terraform ECS Update in place causing bugs

.github/workflows/Deploy-Cluster.yml
=> Remove extra jobs

.github/workflows/Deploy-Cluster.yml
=> Remove extra checkout

.github/workflows/Deploy-Cluster.yml
=> Fix jobs v2

.github/workflows/Deploy-Cluster.yml
=> Fix workflow again

.github/workflows/Deploy-Cluster.yml
=> Working dir fix

.github/workflows/Deploy-Cluster.yml, Terraform/Cluster_Production/alb.tf, Terraform/Cluster_Production/main.tf, Terraform/Cluster_Staging/alb.tf, Terraform/Cluster_Staging/main.tf
Fix name of jobs
Remove mysql depends
lower health check delay
=> Fix Deploy

.github/workflows/Deploy-Cluster.yml
=> add region

.github/workflows/Build-and-Test.yml, .github/workflows/Build-and-Test_Production.yml, .github/workflows/Deploy-Cluster.yml, .github/workflows/Deploy-Cluster_Production.yml, .github/workflows/Deploy-Cluster_ProductionW.yml, .github/workflows/Init-RDS Database.yml, .github/workflows/Init-RDS-Database_Production.yml, .github/workflows/Init-Remote-Statefile.yml, .github/workflows/Init-Remote-Statefile_Production.yml, .github/workflows/Init-Remote-Statefile_ProductionW.yml, .github/workflows/Release-Cluster.yml, .github/workflows/Release-Cluster_Production.yml, .github/workflows/Release-Cluster_ProductionW.yml, Terraform/Cluster_Production/ecs.tf, Terraform/Cluster_Production/route53.tf, Terraform/Cluster_ProductionW/alb.tf, Terraform/Cluster_ProductionW/backend.tf, Terraform/Cluster_ProductionW/ecs.tf, Terraform/Cluster_ProductionW/main.tf, Terraform/Cluster_ProductionW/providers.tf, Terraform/Cluster_ProductionW/route53.tf, Terraform/Cluster_ProductionW/terraform.tfvars, Terraform/Cluster_ProductionW/variables.tf, Terraform/Cluster_ProductionW/vpc.tf
Made code more readable
Added Parallelism to production
Adding Region West
Added Failover
=> Workflow improvements 

.github/workflows/Deploy-Cluster_ProductionW.yml
=> West in Workflow name

Terraform/Cluster_ProductionW/route53.tf
=> Staging -> main

Terraform/Cluster_ProductionW/vpc.tf
=> east -> west
